In [62]:
# 파일명 - 도로형태별 교통사고
# 목표 - 어떤 도로형태에서 사고가 많이 나는지에 대한 정보 확인 하는 것이 1차 목표고 
# 이를 바탕으로 어떤 도로형태에 대해서 좀 더 집중적으로 대비를 하는 것이 좋을지 생각해보는 것이 2차 목표이다.
# 시각화는 연도별 단순 막대그래프, 원차트로 도로형태별 비교를 중점적으로 하면 좋을 것 같은 느낌이다.
# (혹시라도 더 좋은 아이디어 있으면 다른거로 해도 가능)

In [ ]:
import pandas as pd

In [63]:
filename='C:\\rawData\\도로형태별 교통사고.xls'
raw_data=pd.read_excel(filename)

In [64]:
# 2017년 모든 교통사고, 2018년 모든 교통사고, 2019년 모든 교통사고
total_raw_data=raw_data[["도로형태","기준년도","2017년","2018년","2019년","2020년","2021년"]]
pm_raw_data=raw_data[["도로형태","기준년도","2017년.19","2018년.19","2019년.19","2020년.19","2021년.19"]]

In [65]:
pm_raw_data.columns=["도로형태","사고수","2017년","2018년","2019년","2020년","2021년"]
total_raw_data.columns=["도로형태","사고수","2017년","2018년","2019년","2020년","2021년"]

In [66]:
pm_data=pm_raw_data[2:47]

In [67]:
total_data=total_raw_data[2:47]

In [68]:
total_data.replace('-',0,inplace=True)
pm_data.replace('-',0,inplace=True)

C:\Users\UOS\AppData\Local\Temp\ipykernel_12808\1634514462.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total_data.replace('-',0,inplace=True)
C:\Users\UOS\AppData\Local\Temp\ipykernel_12808\1634514462.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm_data.replace('-',0,inplace=True)

In [69]:
# 도로형태별 pm의 부상자수, 사망자수, 사고건수 2017년~2021년
pm_data

         도로형태   사고수  2017년  2018년  2019년  2020년  2021년
2          합계  사고건수    117    225    447    897   1735
3          합계  사망자수      4      4      8     10     19
4          합계  부상자수    124    238    473    985   1901
5          기타  사고건수     22     20      0      0      0
6          기타  사망자수      1      1      0      0      0
7          기타  부상자수     23     21      0      0      0
8        교차로안  사고건수     22     66    119    193    358
9        교차로안  사망자수      0      1      2      4      4
10       교차로안  부상자수     26     74    129    215    414
11   교차로횡단보도내  사고건수      3      5     27     54    113
12   교차로횡단보도내  사망자수      0      0      0      0      1
13   교차로횡단보도내  부상자수      3      5     29     62    121
14      교차로부근  사고건수      7     21     45     76    176
15      교차로부근  사망자수      0      0      1      2      2
16      교차로부근  부상자수      7     21     48     86    194
17      횡단보도상  사고건수      0      0      0      0      0
18      횡단보도상  사망자수      0      0      0      0      0
19      횡단보도상  부상자수      0      0      0      0      0
20     횡단보도부근  사고건수      0      0      0      0      0
21     횡단보도부근  사망자수      0      0      0      0      0
22     횡단보도부근  부상자수      0      0      0      0      0
23         터널  사고건수      0      1      0      0      1
24         터널  사망자수      0      0      0      0      0
25         터널  부상자수      0      1      0      0      1
26         교량  사고건수      1      0      4      4      6
27         교량  사망자수      0      0      0      0      0
28         교량  부상자수      1      0      5      4      6
29      고가도로위  사고건수      0      0      1      1      2
30      고가도로위  사망자수      0      0      0      0      0
31      고가도로위  부상자수      0      0      1      1      2
32      철길건널목  사고건수      0      0      0      0      0
33      철길건널목  사망자수      0      0      0      0      0
34      철길건널목  부상자수      0      0      0      0      0
35  지하차도(도로)내  사고건수      0      4      0      8     11
36  지하차도(도로)내  사망자수      0      0      0      0      0
37  지하차도(도로)내  부상자수      0      4      0      9     12
38         기타  사고건수     62    108    192    446    791
39         기타  사망자수      3      2      5      4      9
40         기타  부상자수     64    112    199    483    866
41         기타  사고건수      0      0     59    115    276
42         기타  사망자수      0      0      0      0      3
43         기타  부상자수      0      0     62    125    284
44        미분류  사고건수      0      0      0      0      1
45        미분류  사망자수      0      0      0      0      0
46        미분류  부상자수      0      0      0      0      1

In [70]:
pm_data_사망자수=pm_data[pm_data['사고수']=="사망자수"]
pm_data_사망자수=pm_data_사망자수[["도로형태","2017년","2018년","2019년","2020년","2021년"]]

In [71]:
pm_data_부상자수=pm_data[pm_data['사고수']=="부상자수"]
pm_data_부상자수=pm_data_부상자수[["도로형태","2017년","2018년","2019년","2020년","2021년"]]

In [72]:
pm_data_사고건수=pm_data[pm_data['사고수']=="사고건수"]
pm_data_사고건수=pm_data_사고건수[["도로형태","2017년","2018년","2019년","2020년","2021년"]]

In [73]:
# 도로형태에 따른 pm의 사망자수 2017년~2021년 
pm_data_사망자수

         도로형태  2017년  2018년  2019년  2020년  2021년
3          합계      4      4      8     10     19
6          기타      1      1      0      0      0
9        교차로안      0      1      2      4      4
12   교차로횡단보도내      0      0      0      0      1
15      교차로부근      0      0      1      2      2
18      횡단보도상      0      0      0      0      0
21     횡단보도부근      0      0      0      0      0
24         터널      0      0      0      0      0
27         교량      0      0      0      0      0
30      고가도로위      0      0      0      0      0
33      철길건널목      0      0      0      0      0
36  지하차도(도로)내      0      0      0      0      0
39         기타      3      2      5      4      9
42         기타      0      0      0      0      3
45        미분류      0      0      0      0      0

In [74]:
# 도로형태에 따른 pm의 부상자수 2017년~2021년 
pm_data_부상자수

         도로형태  2017년  2018년  2019년  2020년  2021년
4          합계    124    238    473    985   1901
7          기타     23     21      0      0      0
10       교차로안     26     74    129    215    414
13   교차로횡단보도내      3      5     29     62    121
16      교차로부근      7     21     48     86    194
19      횡단보도상      0      0      0      0      0
22     횡단보도부근      0      0      0      0      0
25         터널      0      1      0      0      1
28         교량      1      0      5      4      6
31      고가도로위      0      0      1      1      2
34      철길건널목      0      0      0      0      0
37  지하차도(도로)내      0      4      0      9     12
40         기타     64    112    199    483    866
43         기타      0      0     62    125    284
46        미분류      0      0      0      0      1

In [75]:
# 도로형태에 따른 pm의 사고건수 2017년~2021년 
pm_data_사고건수

         도로형태  2017년  2018년  2019년  2020년  2021년
2          합계    117    225    447    897   1735
5          기타     22     20      0      0      0
8        교차로안     22     66    119    193    358
11   교차로횡단보도내      3      5     27     54    113
14      교차로부근      7     21     45     76    176
17      횡단보도상      0      0      0      0      0
20     횡단보도부근      0      0      0      0      0
23         터널      0      1      0      0      1
26         교량      1      0      4      4      6
29      고가도로위      0      0      1      1      2
32      철길건널목      0      0      0      0      0
35  지하차도(도로)내      0      4      0      8     11
38         기타     62    108    192    446    791
41         기타      0      0     59    115    276
44        미분류      0      0      0      0      1