In [2]:
# 파일명 - 도로종류별 교통사고
# 목표 - 어떤 도로에서 사고가 많이 나는지에 대한 정보 확인 하는 것이 1차 목표고 
# 이를 바탕으로 어떤 도로에서 좀 더 집중적으로 감시를 해서 사고를 예방해야할지 대책을 세우는 것이 2차 목표이다.
# 근데 이 데이터는 좀 쓰기가 애매한 것 같은 느낌이 있음. 뭔가 유용한 정보는 아닌거 같은 느낌?
# 시각화는 연도별 단순 막대그래프, 원차트로 도로형태별 비교를 중점적으로 하면 좋을 것 같은 느낌이다.
# (혹시라도 더 좋은 아이디어 있으면 다른거로 해도 가능)

In [3]:
import pandas as pd

In [4]:
filename='C:\\rawData\\도로종류별 교통사고.xls'
raw_data=pd.read_excel(filename)

In [5]:
raw_data

,도로종류,기준년도,2017년,2017년.1,2017년.2,2017년.3,2017년.4,2017년.5,2017년.6,2017년.7,...,2021년.21,2021년.22,2021년.23,2021년.24,2021년.25,2021년.26,2021년.27,2021년.28,2021년.29,2021년.30
0,도로종류,기준년도,합계,합계,합계,합계,합계,합계,합계,합계,...,건설기계,건설기계,농기계,농기계,보행자,보행자,기타,기타,미분류,미분류
1,도로종류,기준년도,합계,승용,승합,화물,특수,이륜,원동기,기타,...,합계,기타,합계,기타,합계,기타,합계,기타,합계,기타
2,합계,사고건수,1143175,163058,39801,43658,1111,22080,4690,868777,...,2677,2677,389,389,9520,9520,429701,429701,431680,431680
3,합계,사망자수,4185,2048,286,961,29,406,121,334,...,79,79,62,62,0,0,7,7,0,0
4,합계,부상자수,1803325,253046,61731,65786,1773,25668,5530,1389791,...,3796,3796,426,426,11072,11072,666884,666884,800993,800993
5,일반국도,사고건수,34445,11463,1986,13616,138,1049,280,5913,...,422,422,34,34,8,8,2096,2096,4066,4066
6,일반국도,사망자수,722,369,37,205,4,69,9,29,...,16,16,1,1,0,0,1,1,0,0
7,일반국도,부상자수,56707,19803,3536,20658,240,1221,322,10927,...,644,644,48,48,22,22,4563,4563,9513,9513
8,지방도,사고건수,51480,10815,1300,3058,79,1112,252,34864,...,215,215,49,49,1,1,687,687,483,483
9,지방도,사망자수,571,286,22,142,3,61,14,43,...,9,9,10,10,0,0,0,0,0,0
10,지방도,부상자수,83354,17193,2410,4734,153,1325,279,57260,...,302,302,52,52,4,4,1422,1422,1424,1424
11,특별광역시도,사고건수,104914,64463,8115,8237,343,7670,2347,13739,...,800,800,12,12,4,4,6806,6806,2718,2718
12,특별광역시도,사망자수,982,529,74,159,7,108,30,75,...,29,29,2,2,0,0,1,1,0,0
13,특별광역시도,부상자수,153934,95669,12400,11577,517,9296,2835,21640,...,1123,1123,14,14,13,13,11935,11935,8170,8170
14,시도,사고건수,153210,53504,14498,9091,320,4838,1394,69565,...,726,726,101,101,65,65,46936,46936,20292,20292
15,시도,사망자수,1210,620,106,236,8,114,40,86,...,14,14,15,15,0,0,3,3,0,0
16,시도,부상자수,251975,82461,22346,13475,457,5817,1659,125760,...,1038,1038,112,112,139,139,78244,78244,51467,51467
17,군도,사고건수,8614,4660,382,1842,34,715,263,718,...,93,93,85,85,-,-,106,106,43,43
18,군도,사망자수,301,94,17,80,4,38,19,49,...,2,2,13,13,-,-,1,1,0,0
19,군도,부상자수,12489,7226,661,2621,40,785,274,882,...,130,130,91,91,-,-,175,175,143,143
20,고속국도,사고건수,12160,3010,866,4217,130,3,-,3934,...,93,93,-,-,1,1,508,508,4183,4183
21,고속국도,사망자수,248,113,24,106,3,0,-,2,...,3,3,-,-,0,0,0,0,0,0
22,고속국도,부상자수,27315,6800,3334,7723,268,4,-,9186,...,169,169,-,-,2,2,1530,1530,10773,10773
23,기타,사고건수,433759,14658,12623,3549,66,6683,154,396026,...,206,206,98,98,150,150,359997,359997,127038,127038
24,기타,사망자수,151,37,6,33,0,16,9,50,...,6,6,21,21,0,0,1,1,0,0
25,기타,부상자수,689415,23132,17001,4932,97,7210,161,636882,...,265,265,98,98,464,464,551720,551720,286958,286958
26,미분류,사고건수,344593,485,31,48,1,10,-,344018,...,122,122,10,10,9291,9291,12565,12565,272857,272857
27,미분류,사망자수,0,0,0,0,0,0,-,0,...,0,0,0,0,0,0,0,0,0,0
28,미분류,부상자수,528136,762,43,66,1,10,-,527254,...,125,125,11,11,10428,10428,17295,17295,432545,432545
29,출처) 도로교통공단.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# 2017년 모든 교통사고, 2018년 모든 교통사고, 2019년 모든 교통사고
total_raw_data=raw_data[["도로종류","기준년도","2017년","2018년","2019년","2020년","2021년"]]
pm_raw_data=raw_data[["도로종류","기준년도","2017년.19","2018년.19","2019년.19","2020년.19","2021년.19"]]

In [7]:
pm_raw_data

,도로종류,기준년도,2017년.19,2018년.19,2019년.19,2020년.19,2021년.19
0,도로종류,기준년도,개인형이동수단(PM),개인형이동수단(PM),개인형이동수단(PM),개인형이동수단(PM),개인형이동수단(PM)
1,도로종류,기준년도,합계,합계,합계,합계,합계
2,합계,사고건수,117,225,447,897,1735
3,합계,사망자수,4,4,8,10,19
4,합계,부상자수,124,238,473,985,1901
5,일반국도,사고건수,4,5,18,30,88
6,일반국도,사망자수,1,0,0,1,1
7,일반국도,부상자수,3,5,20,33,94
8,지방도,사고건수,5,10,17,23,73
9,지방도,사망자수,0,1,1,1,0
10,지방도,부상자수,5,9,18,27,80
11,특별광역시도,사고건수,57,110,235,528,754
12,특별광역시도,사망자수,1,0,2,4,5
13,특별광역시도,부상자수,63,119,251,572,841
14,시도,사고건수,32,70,125,222,552
15,시도,사망자수,0,3,4,4,8
16,시도,부상자수,33,74,128,245,599
17,군도,사고건수,4,5,4,10,23
18,군도,사망자수,0,0,1,0,1
19,군도,부상자수,6,6,3,11,25
20,고속국도,사고건수,-,-,-,-,-
21,고속국도,사망자수,-,-,-,-,-
22,고속국도,부상자수,-,-,-,-,-
23,기타,사고건수,15,25,48,84,245
24,기타,사망자수,2,0,0,0,4
25,기타,부상자수,14,25,53,97,262
26,미분류,사고건수,-,-,-,-,-
27,미분류,사망자수,-,-,-,-,-
28,미분류,부상자수,-,-,-,-,-
29,출처) 도로교통공단.,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
pm_raw_data.columns=["도로종류","사고수","2017년","2018년","2019년","2020년","2021년"]
total_raw_data.columns=["도로종류","사고수","2017년","2018년","2019년","2020년","2021년"]

In [9]:
pm_data=pm_raw_data[2:29]
total_data=total_raw_data[2:29]

In [10]:
total_data.replace('-',0,inplace=True)
pm_data.replace('-',0,inplace=True)

C:\Users\UOS\AppData\Local\Temp\ipykernel_10532\1634514462.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total_data.replace('-',0,inplace=True)
C:\Users\UOS\AppData\Local\Temp\ipykernel_10532\1634514462.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm_data.replace('-',0,inplace=True)

In [11]:
pm_data_사망자수=pm_data[pm_data['사고수']=="사망자수"]
pm_data_사망자수=pm_data_사망자수[["도로종류","2017년","2018년","2019년","2020년","2021년"]]

In [12]:
pm_data_부상자수=pm_data[pm_data['사고수']=="부상자수"]
pm_data_부상자수=pm_data_부상자수[["도로종류","2017년","2018년","2019년","2020년","2021년"]]

In [13]:
pm_data_사고건수=pm_data[pm_data['사고수']=="사고건수"]
pm_data_사고건수=pm_data_사고건수[["도로종류","2017년","2018년","2019년","2020년","2021년"]]

In [14]:
# 도로종류에 따른 pm의 사망자수 2017년~2021년 
pm_data_사망자수

      도로종류  2017년  2018년  2019년  2020년  2021년
3       합계      4      4      8     10     19
6     일반국도      1      0      0      1      1
9      지방도      0      1      1      1      0
12  특별광역시도      1      0      2      4      5
15      시도      0      3      4      4      8
18      군도      0      0      1      0      1
21    고속국도      0      0      0      0      0
24      기타      2      0      0      0      4
27     미분류      0      0      0      0      0

In [15]:
# 도로종류에 따른 pm의 부상자수 2017년~2021년 
pm_data_부상자수

      도로종류  2017년  2018년  2019년  2020년  2021년
4       합계    124    238    473    985   1901
7     일반국도      3      5     20     33     94
10     지방도      5      9     18     27     80
13  특별광역시도     63    119    251    572    841
16      시도     33     74    128    245    599
19      군도      6      6      3     11     25
22    고속국도      0      0      0      0      0
25      기타     14     25     53     97    262
28     미분류      0      0      0      0      0

In [16]:
# 도로종류에 따른 pm의 사고건수 2017년~2021년 
pm_data_사고건수

      도로종류  2017년  2018년  2019년  2020년  2021년
2       합계    117    225    447    897   1735
5     일반국도      4      5     18     30     88
8      지방도      5     10     17     23     73
11  특별광역시도     57    110    235    528    754
14      시도     32     70    125    222    552
17      군도      4      5      4     10     23
20    고속국도      0      0      0      0      0
23      기타     15     25     48     84    245
26     미분류      0      0      0      0      0